# NumPy

NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of NumPy, focusing on arrays and vectorized operations.

In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

#create arrays using numpy
#create a 1D Array
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [4]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5)   #1 row and 5 col

array([[1, 2, 3, 4, 5]])

In [5]:
# 2D Array or Matrix
arr2 = np.array([[1,2,3,4,5], [2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [6]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [7]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
# Identity Matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
# Attributes of Numpy Array
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Shape:", arr.shape)  # Output: (2, 3)
print("Number of dimensions:", arr.ndim)  # Output: 2
print("Size (number of elements):", arr.size)  # Output: 6
print("Data type:", arr.dtype)  # Output: int64v (may vary based on platform)
print("Item size (in bytes):", arr.itemsize)  # Output: 8 (may vary based on platform)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int64
Item size (in bytes): 8


In [10]:
# Numpy Vectorized Operation
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

# Element Wise addition
print("Addition:", arr1+arr2)

# Element Wise Substraction
print("Subtraction:", arr1-arr2)

# Element-wise multiplication
print("Multiplication:", arr1 * arr2)

# Element-wise division
print("Division:", arr1 / arr2)

Addition: [11 22 33 44 55]
Subtraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [11]:
# Universal Functions
arr = np.array([2,3,4,5,6])

# Square root
print(np.sqrt(arr))

# Exponential
print(np.exp(arr))

# Sine
print(np.sin(arr))

# natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [12]:
# Array Slicing and Indexing

arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array : \n", arr)

print("\nArray Slicing\n")
print(arr[1:,1:3])

print(arr[0][0])
print(arr[0:2,2:])

arr[1:,2:]

Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Array Slicing

[[ 6  7]
 [10 11]]
1
[[3 4]
 [7 8]]


array([[ 7,  8],
       [11, 12]])

In [13]:
# Modify array elements
arr[0,0] = 100
print(arr)

arr[1:] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [14]:
# Statistical concepts--Normalization
# to have a mean of 0 and standard deviation of 1
data = np.array([1, 2, 3, 4, 5])

# Calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
normalized_data = (data - mean) / std_dev
print("Normalized data:", normalized_data)

Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [15]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Mean
mean = np.mean(data)
print("Mean:", mean)

# Median
median = np.median(data)
print("Median:", median)

# Standard deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# Variance
variance = np.var(data)
print("Variance:", variance)


Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [16]:
# Logical Operations

data = np.array([1,2,3,4,5,6,7,8,9,10])

data[(data >= 5) & (data <= 8)]


array([5, 6, 7, 8])

In [17]:
np.linspace(3, 5)

array([3.        , 3.04081633, 3.08163265, 3.12244898, 3.16326531,
       3.20408163, 3.24489796, 3.28571429, 3.32653061, 3.36734694,
       3.40816327, 3.44897959, 3.48979592, 3.53061224, 3.57142857,
       3.6122449 , 3.65306122, 3.69387755, 3.73469388, 3.7755102 ,
       3.81632653, 3.85714286, 3.89795918, 3.93877551, 3.97959184,
       4.02040816, 4.06122449, 4.10204082, 4.14285714, 4.18367347,
       4.2244898 , 4.26530612, 4.30612245, 4.34693878, 4.3877551 ,
       4.42857143, 4.46938776, 4.51020408, 4.55102041, 4.59183673,
       4.63265306, 4.67346939, 4.71428571, 4.75510204, 4.79591837,
       4.83673469, 4.87755102, 4.91836735, 4.95918367, 5.        ])

In [26]:
# Boolean Indexing
a = np.array([10, 20, 30, 40, 50])
a[a < 25]


array([10, 20])

In [22]:
a[(a > 20) & (a < 50)]

array([30, 40])

In [ ]:
# Fancy Indexing
arr = np.array([10, 20, 30, 40, 50])
indices = [0, 2, 4]
arr[indices]  # Output: array([10, 30, 50])

array([10, 30, 50])

In [27]:
# View vs Copy
arr = np.array([1, 2, 3, 4, 5])
view_arr = arr.view()
copy_arr = arr.copy()
view_arr[0] = 100
print("Original array after modifying view:", arr)  # arr is affected
copy_arr[1] = 200
print("Original array after modifying copy:", arr)  # arr is not affected   


Original array after modifying view: [100   2   3   4   5]
Original array after modifying copy: [100   2   3   4   5]


In [ ]:
# Axis Concept is a core idea in NumPy that helps in performing operations along specific dimensions of an array.
arr = np.array([[1, 2, 3], [4, 5, 6]])
# Sum along columns (axis=0)
col = np.sum(arr, axis=0)
print(col)

# Sum along rows (axis=1)
row = np.sum(arr, axis=1)
print(row)

[5 7 9]
[ 6 15]


In [ ]:
# Vectorized Operations
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print ("sum : ", a + b)  # Output: array([5, 7, 9])
print ("product : ", a * b)  # Output: array([ 4, 10, 18])  
print ("difference : ", a - b)  # Output: array([-3, -3, -3])
print ("division : ", a / b)  # Output: array([0.25, 0.4 , 0.5])

sum :  [5 7 9]
product :  [ 4 10 18]
difference :  [-3 -3 -3]
division :  [0.25 0.4  0.5 ]


In [35]:
# Universal Functions
arr = np.array([1,2,3]) 

print("Square root :", np.sqrt(arr))
print("Exponential :", np.exp(arr))
print("Sine :", np.sin(arr))
print("Natural log :", np.log(arr))


Square root : [1.         1.41421356 1.73205081]
Exponential : [ 2.71828183  7.3890561  20.08553692]
Sine : [0.84147098 0.90929743 0.14112001]
Natural log : [0.         0.69314718 1.09861229]


In [ ]:
# Broadcasting
# Broadcasting Rules (Interview)

# 1. Compare shapes from right to left
# 2. Dimensions must match or be 1 
# 3. Else → error

A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([10, 20, 30])
C = A + B
print(C)


[[11 22 33]
 [14 25 36]]


In [38]:
# Statistics Functions
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])    

print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Standard Deviation:", np.std(data))
print("Variance:", np.var(data))


Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [43]:
# Linear Algebra 
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Matrix Addition
C = A + B
print("Matrix Addition:\n", C)

# Matrix Multiplication
D = np.dot(A, B)
print("Matrix Multiplication:\n", D)

print("Matrix Multiplication alternative:\n", A @ B)  
# Transpose
E = A.T
print("Transpose of A:\n", E)

# Inverse & Determinant
F = np.linalg.inv(A)
print("Inverse of A:\n", F) 
det_A = np.linalg.det(A)
print("Determinant of A:", det_A)

# Solve Equations
# Example: Solve the system of equations
# 2x + 3y = 8
# 5x + 4y = 13
coeff_matrix = np.array([[2, 3], [5, 4]])
const_matrix = np.array([8, 13])
solution = np.linalg.solve(coeff_matrix, const_matrix)
print("Solution (x, y):", solution) 




Matrix Addition:
 [[ 6  8]
 [10 12]]
Matrix Multiplication:
 [[19 22]
 [43 50]]
Matrix Multiplication alternative:
 [[19 22]
 [43 50]]
Transpose of A:
 [[1 3]
 [2 4]]
Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Determinant of A: -2.0000000000000004
Solution (x, y): [1. 2.]
