In [2]:
import torch
print(torch.__version__)

2.12.0


## Check GPU or CPU

In [3]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU not available. Using CPU.


## Creating Tensor

In [6]:
a = torch.empty(2,3)
type(a)

torch.Tensor

In [7]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
# using random numbers
torch.rand(2,3)

tensor([[0.9671, 0.1410, 0.9666],
        [0.0955, 0.4337, 0.5730]])

In [9]:
# use of seed
torch.rand(2,3)

tensor([[0.2114, 0.8140, 0.5561],
        [0.7801, 0.1926, 0.7598]])

In [10]:
# manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [11]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [12]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [13]:
# other ways

# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,10))

# using eye
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3, 3), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Tensor Shapes

In [14]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [15]:
x.shape

torch.Size([2, 3])

In [16]:
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [17]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [18]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [19]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

## Tensor Data Types

In [20]:
x.dtype

torch.int64

In [21]:
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [22]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [23]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


## Mathematical operations

### 1. Scalar operation

In [24]:
x = torch.rand(2,2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [25]:
# addition
x + 2

tensor([[2.7118, 2.7876],
        [2.4183, 2.9014]])

In [26]:
# substraction
x - 2

tensor([[-1.2882, -1.2124],
        [-1.5817, -1.0986]])

In [27]:
# multiplication
x * 3

tensor([[2.1353, 2.3627],
        [1.2549, 2.7042]])

In [28]:
# division
x / 3

tensor([[0.2373, 0.2625],
        [0.1394, 0.3005]])

In [29]:
# int division
(x * 100)//3

tensor([[23., 26.],
        [13., 30.]])

In [30]:
# mod
((x * 100)//3)%2

tensor([[1., 0.],
        [1., 0.]])

In [31]:
# power
x**2

tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])

### 2. Element wise operation

In [55]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.0447, 0.5123, 0.9051],
        [0.5989, 0.4450, 0.7278]])
tensor([[0.4563, 0.3389, 0.6211],
        [0.5530, 0.6896, 0.3687]])


In [56]:
print("Addition: ", a + b)
print("\nSubtraction: ", a - b)
print("\nMultiplication: ", a * b)
print("\nDivision: ", a / b)
print("\nPower: ", a ** b)
print("\nMod: ", a % b)

Addition:  tensor([[0.5009, 0.8512, 1.5262],
        [1.1519, 1.1346, 1.0966]])

Subtraction:  tensor([[-0.4116,  0.1735,  0.2839],
        [ 0.0458, -0.2446,  0.3591]])

Multiplication:  tensor([[0.0204, 0.1736, 0.5622],
        [0.3312, 0.3069, 0.2684]])

Division:  tensor([[0.0979, 1.5119, 1.4571],
        [1.0829, 0.6453, 1.9738]])

Power:  tensor([[0.2421, 0.7972, 0.9399],
        [0.7531, 0.5722, 0.8895]])

Mod:  tensor([[0.0447, 0.1735, 0.2839],
        [0.0458, 0.4450, 0.3591]])


In [58]:
c = torch.tensor([1, -2, 3, -4])
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

print("\nAbs: ", torch.abs(c))
print("\nNegative: ", torch.neg(c))
print("\nRound: ", torch.round(d))
print("\nCeil: ", torch.ceil(d))
print("\nFloor: ", torch.floor(d))
print("\nClamp: ", torch.clamp(d, min=2, max=3))


Abs:  tensor([1, 2, 3, 4])

Negative:  tensor([-1,  2, -3,  4])

Round:  tensor([2., 2., 4., 4.])

Ceil:  tensor([2., 3., 4., 5.])

Floor:  tensor([1., 2., 3., 4.])

Clamp:  tensor([2.0000, 2.3000, 3.0000, 3.0000])


### 3. Reduction operation

In [48]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[8., 0., 7.],
        [0., 0., 9.]])

In [66]:
print("Sum: ", torch.sum(e))
print("\nSum along columns: ", torch.sum(e, dim=0))
print("\nSum along rows: ", torch.sum(e, dim=1))

Sum:  tensor(24.)

Sum along columns:  tensor([ 8.,  0., 16.])

Sum along rows:  tensor([15.,  9.])


In [61]:
print("Mean: ", torch.mean(e))
print("\nMean along columns: ", torch.mean(e, dim=0))
print("\nMean along rows: ", torch.mean(e, dim=1))

Mean:  tensor(4.)

Mean along columns:  tensor([4., 0., 8.])

Mean along rows:  tensor([5., 3.])


In [62]:
print("Median: ", torch.median(e))
print("\nMedian along columns: ", torch.median(e, dim=0))
print("\nMedian along rows: ", torch.median(e, dim=1))

Median:  tensor(0.)

Median along columns:  torch.return_types.median(
values=tensor([0., 0., 7.]),
indices=tensor([1, 0, 0]))

Median along rows:  torch.return_types.median(
values=tensor([7., 0.]),
indices=tensor([2, 1]))


In [65]:
print("Max: ", torch.max(e))
print("\nMax along columns: ", torch.max(e, dim=0))
print("\nMax along rows: ", torch.max(e, dim=1))

Max:  tensor(9.)

Max along columns:  torch.return_types.max(
values=tensor([8., 0., 9.]),
indices=tensor([0, 0, 1]))

Max along rows:  torch.return_types.max(
values=tensor([8., 9.]),
indices=tensor([0, 2]))


In [64]:
print("Min: ", torch.min(e))
print("\nMin along columns: ", torch.min(e, dim=0))
print("\nMin along rows: ", torch.min(e, dim=1))

Min:  tensor(0.)

Min along columns:  torch.return_types.min(
values=tensor([0., 0., 7.]),
indices=tensor([1, 0, 0]))

Min along rows:  torch.return_types.min(
values=tensor([0., 0.]),
indices=tensor([1, 0]))


In [ ]:
print("Prod: ", torch.prod(e))
print("\nProd along columns: ", torch.prod(e, dim=0))
print("\nProd along rows: ", torch.prod(e, dim=1))

Prod:  tensor(0.)

Prod along columns:  tensor([ 0.,  0., 63.])

Prod along rows:  tensor([0., 0.])


In [67]:
print("Standard Deviation: ", torch.std(e))
print("\nVariance: ", torch.var(e))
print("\nArgMax", torch.argmax(e))
print("\nArgMin", torch.argmin(e))

Standard Deviation:  tensor(4.4272)

Variance:  tensor(19.6000)

ArgMax tensor(5)

ArgMin tensor(1)


### 4. Matrix operations

In [68]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[6, 1, 5],
        [5, 0, 4]])
tensor([[3, 8],
        [8, 3],
        [3, 5]])


In [69]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[41, 76],
        [27, 60]])

In [70]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [71]:
# transpose
torch.transpose(f, 0, 1)

tensor([[6, 5],
        [1, 0],
        [5, 4]])

In [72]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[0., 6., 4.],
        [0., 8., 4.],
        [7., 2., 3.]])

In [73]:
# determinant
torch.det(h)

tensor(-56.0000)

In [74]:
# inverse
torch.inverse(h)

tensor([[-0.2857,  0.1786,  0.1429],
        [-0.5000,  0.5000,  0.0000],
        [ 1.0000, -0.7500,  0.0000]])

### 5. Comparison operations

In [75]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[8, 5, 6],
        [2, 9, 5]])
tensor([[0, 4, 2],
        [7, 1, 1]])


In [77]:
print("Greater than:\n", i > j)
print("Less than:\n", i < j)
print("Equal to:\n", i == j)
print("Not equal to:\n", i != j)
print("Greater than equal to:\n", i >= j)
print("Less than equal to:\n", i <= j)

Greater than:
 tensor([[ True,  True,  True],
        [False,  True,  True]])
Less than:
 tensor([[False, False, False],
        [ True, False, False]])
Equal to:
 tensor([[False, False, False],
        [False, False, False]])
Not equal to:
 tensor([[True, True, True],
        [True, True, True]])
Greater than equal to:
 tensor([[ True,  True,  True],
        [False,  True,  True]])
Less than equal to:
 tensor([[False, False, False],
        [ True, False, False]])


### 6. Special functions

In [76]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[5., 4., 4.],
        [1., 1., 2.]])

In [78]:
# log
torch.log(k)

tensor([[1.6094, 1.3863, 1.3863],
        [0.0000, 0.0000, 0.6931]])

In [79]:
# exp
torch.exp(k)

tensor([[148.4132,  54.5982,  54.5982],
        [  2.7183,   2.7183,   7.3891]])

In [80]:
# sqrt
torch.sqrt(k)

tensor([[2.2361, 2.0000, 2.0000],
        [1.0000, 1.0000, 1.4142]])

In [81]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9933, 0.9820, 0.9820],
        [0.7311, 0.7311, 0.8808]])

In [82]:
# softmax
torch.softmax(k, dim=0)

tensor([[0.9820, 0.9526, 0.8808],
        [0.0180, 0.0474, 0.1192]])

In [83]:
# relu
torch.relu(k)

tensor([[5., 4., 4.],
        [1., 1., 2.]])

## Inplace Operations

In [84]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.9186, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])
tensor([[0.4175, 0.0340, 0.9157],
        [0.3079, 0.6269, 0.8277]])


In [85]:
m.add_(n)

tensor([[1.3361, 0.2472, 1.3114],
        [0.9096, 1.0504, 1.3501]])

In [86]:
m

tensor([[1.3361, 0.2472, 1.3114],
        [0.9096, 1.0504, 1.3501]])

In [87]:
n

tensor([[0.4175, 0.0340, 0.9157],
        [0.3079, 0.6269, 0.8277]])

In [88]:
torch.relu(m)

tensor([[1.3361, 0.2472, 1.3114],
        [0.9096, 1.0504, 1.3501]])

In [89]:
m.relu_()

tensor([[1.3361, 0.2472, 1.3114],
        [0.9096, 1.0504, 1.3501]])

In [90]:
m

tensor([[1.3361, 0.2472, 1.3114],
        [0.9096, 1.0504, 1.3501]])

## Copying a Tensor

In [91]:
a = torch.rand(2,3)
a

tensor([[0.6594, 0.0887, 0.4890],
        [0.5887, 0.7340, 0.8497]])

In [92]:
b = a

In [93]:
b

tensor([[0.6594, 0.0887, 0.4890],
        [0.5887, 0.7340, 0.8497]])

In [94]:
a[0][0] = 0

In [95]:
a

tensor([[0.0000, 0.0887, 0.4890],
        [0.5887, 0.7340, 0.8497]])

In [96]:
b

tensor([[0.0000, 0.0887, 0.4890],
        [0.5887, 0.7340, 0.8497]])

In [98]:
print(id(a))
print(id(b))

4913146256
4913146256


In [99]:
b = a.clone()

In [100]:
a

tensor([[0.0000, 0.0887, 0.4890],
        [0.5887, 0.7340, 0.8497]])

In [101]:
b

tensor([[0.0000, 0.0887, 0.4890],
        [0.5887, 0.7340, 0.8497]])

In [102]:
a[0][0] = 10

In [103]:
a

tensor([[10.0000,  0.0887,  0.4890],
        [ 0.5887,  0.7340,  0.8497]])

In [104]:
b

tensor([[0.0000, 0.0887, 0.4890],
        [0.5887, 0.7340, 0.8497]])

In [105]:
print(id(a))
print(id(b))

4913146256
4913204352
