## Spam Ham Classification Project Using TF-IDF And ML

In [3]:
import pandas as pd
messages = pd.read_csv('../08_NLP_ML/SMSSpamCollection.txt', sep='\t',names=["label","message"])
messages

,label,message
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."
...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...
5568,ham,Will ü b going to esplanade fr home?
5569,ham,"Pity, * was in mood for that. So...any other s..."
5570,ham,The guy did some bitching but I acted like i'd...


In [4]:
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/vmangla/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [5]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [6]:
corpus=[]
for i in range(0,len(messages)):
    review = re.sub('[^a-zA-z]', ' ', messages['message'][i])
    review = review.lower()
    review = review.split()
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [7]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather

### Create Bag Of Words

In [8]:
## Create the Bag OF Words model
from sklearn.feature_extraction.text import CountVectorizer
## for Binary BOW enable binary=True
cv = CountVectorizer(max_features=2500, ngram_range=(1,2))

In [11]:
import numpy as np
np.set_printoptions(edgeitems=30, linewidth=100000, formatter=dict(float=lambda x: "%.3g" % x))
X = cv.fit_transform(corpus).toarray()
X

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

In [12]:
cv.vocabulary_

{'go': np.int64(791),
 'point': np.int64(1619),
 'crazi': np.int64(451),
 'avail': np.int64(112),
 'bugi': np.int64(237),
 'great': np.int64(858),
 'world': np.int64(2441),
 'la': np.int64(1104),
 'cine': np.int64(354),
 'got': np.int64(839),
 'wat': np.int64(2355),
 'ok': np.int64(1463),
 'lar': np.int64(1115),
 'joke': np.int64(1074),
 'wif': np.int64(2407),
 'oni': np.int64(1484),
 'ok lar': np.int64(1466),
 'free': np.int64(719),
 'entri': np.int64(622),
 'wkli': np.int64(2431),
 'comp': np.int64(402),
 'win': np.int64(2412),
 'cup': np.int64(468),
 'final': np.int64(687),
 'st': np.int64(2017),
 'may': np.int64(1266),
 'text': np.int64(2121),
 'receiv': np.int64(1734),
 'question': np.int64(1692),
 'std': np.int64(2030),
 'txt': np.int64(2231),
 'rate': np.int64(1709),
 'appli': np.int64(76),
 'free entri': np.int64(724),
 'entri wkli': np.int64(624),
 'cup final': np.int64(469),
 'std txt': np.int64(2031),
 'txt rate': np.int64(2237),
 'rate appli': np.int64(1711),
 'dun': np.int

In [13]:
y = pd.get_dummies(messages['label'])

In [14]:
y = y.iloc[:,0].values

In [15]:
y.shape

(5572,)

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)
X_train.shape, X_test.shape, y_test.shape, y_test.shape

((4457, 2500), (1115, 2500), (1115,), (1115,))

In [20]:
from sklearn.naive_bayes import MultinomialNB
spam_detect_model = MultinomialNB()
spam_detect_model.fit(X_train, y_train)

y_pred = spam_detect_model.predict(X_test)
y_pred[:10]

array([False,  True,  True,  True,  True, False,  True,  True,  True,  True])

In [22]:
from sklearn.metrics import accuracy_score, classification_report
print("Accuracy Score: ", accuracy_score(y_test, y_pred))
print("Classification Report: \n", classification_report(y_test,y_pred))


Accuracy Score:  0.9883408071748879
Classification Report: 
               precision    recall  f1-score   support

       False       0.98      0.93      0.95       144
        True       0.99      1.00      0.99       971

    accuracy                           0.99      1115
   macro avg       0.98      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115



### Creating The TF-IDF Model

In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(corpus, y, test_size=0.20)

In [27]:
from sklearn.feature_extraction.text import TfidfVectorizer
tv = TfidfVectorizer(max_features=2500 ,ngram_range=(1,2))

X_train = tv.fit_transform(X_train).toarray()
X_test = tv.transform(X_test).toarray()

In [30]:
X_train[:10]

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0.54, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0

In [31]:
tv.vocabulary_

{'ha': np.int64(897),
 'say': np.int64(1801),
 'read': np.int64(1697),
 'anyth': np.int64(73),
 'way': np.int64(2346),
 'seem': np.int64(1826),
 'like': np.int64(1159),
 'save': np.int64(1799),
 'friday': np.int64(749),
 'pub': np.int64(1659),
 'urgent': np.int64(2264),
 'tri': np.int64(2179),
 'contact': np.int64(414),
 'today': np.int64(2143),
 'draw': np.int64(571),
 'show': np.int64(1878),
 'prize': np.int64(1647),
 'guarante': np.int64(884),
 'call': np.int64(242),
 'land': np.int64(1101),
 'line': np.int64(1165),
 'claim': np.int64(344),
 'valid': np.int64(2282),
 'hr': np.int64(985),
 'urgent tri': np.int64(2270),
 'tri contact': np.int64(2181),
 'contact today': np.int64(420),
 'today draw': np.int64(2145),
 'draw show': np.int64(573),
 'show prize': np.int64(1879),
 'prize guarante': np.int64(1650),
 'guarante call': np.int64(886),
 'call land': np.int64(256),
 'land line': np.int64(1102),
 'line claim': np.int64(1166),
 'claim valid': np.int64(350),
 'valid hr': np.int64(2283

In [32]:
from sklearn.naive_bayes import MultinomialNB
spam_tfidf_model = MultinomialNB()
spam_tfidf_model.fit(X_train, y_train)

y_pred = spam_tfidf_model.predict(X_test)
y_pred

array([ True,  True,  True, False,  True,  True,  True,  True, False,  True,  True,  True,  True,  True,  True, False,  True,  True,  True,  True,  True, False,  True,  True,  True,  True,  True,  True,  True,  True, ...,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True, False,  True,  True,  True,  True,  True,  True,  True,  True, False,  True, False,  True,  True,  True, False], shape=(1115,))

In [33]:
score = accuracy_score(y_test,y_pred)
print(score)

0.9748878923766816


In [34]:
from sklearn.metrics import classification_report
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

       False       0.84      0.99      0.91       136
        True       1.00      0.97      0.99       979

    accuracy                           0.97      1115
   macro avg       0.92      0.98      0.95      1115
weighted avg       0.98      0.97      0.98      1115

